#!/usr/bin/perl
#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer Enterprise
# All rights are reserved
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-freepbx-update and nethserver-freepbx-save event
#
event_templates('nethserver-freepbx-update', qw(
   /etc/httpd/conf.d/freepbx.conf
   /etc/httpd/fpbx-conf/httpd.conf
   /etc/opt/rh/rh-php56/php-fpm.d/www.conf
));

event_actions('nethserver-freepbx-update', qw(
    initialize-default-databases        00
    install-freepbx                     50
));

event_services('nethserver-freepbx-update', qw(
    httpd restart
    httpd-fpbx restart
    rh-php56-php-fpm restart
));

#do backup in pre-backup
event_link("nethserver-freepbx-backup", "pre-backup-config", "80");

#remove backup files in post-backup-config
event_link("nethserver-freepbx-backup-delete", "post-backup-config", "90");

#restore backup in post-restore
event_link("nethserver-freepbx-backup-restore", "post-restore-config", "80");

#launch backup restore on package update/upgrade
event_link("nethserver-freepbx-backup-restore", "nethserver-freepbx-update", "70");
