#!/bin/bash

# check if fpbx is installed in a better way
if [[ -d /var/www/html/freepbx ]] ; then
    exit 0
fi

#new install call install
echo " *** Installing FreePBX *** see /var/log/freepbx_rpm_install.log"
echo " *** Installing FreePBX" >> /var/log/freepbx_rpm_install.log
/usr/bin/date >> /var/log/freepbx_rpm_install.log

mkdir -p /var/lib/asterisk/sounds/custom/

# wait for asterisk
systemctl start asterisk
for i in $(seq 0 300); do
    /usr/sbin/asterisk -rx "core show version" 2>1 > /dev/null
    if [[ $(echo $?) == 0 ]] ; then
        break
    fi
    sleep 1
done

touch /var/log/asterisk/fail2ban
touch /var/log/asterisk/freepbx_security.log
touch /var/log/asterisk/cdr-csv/Master.csv
touch /etc/asterisk/pjsip_wizard.conf

chmod 666 /var/log/asterisk/cdr-csv/Master.csv
chmod 755 /var/spool/asterisk/monitor

mkdir -p /var/log/pbx/install
mkdir -p /var/log/pbx/upgrade

mkdir -p /etc/asterisk/keys

chown -R asterisk:asterisk /var/run/asterisk /var/log/pbx /var/lib/asterisk/sounds /etc/asterisk /var/log/asterisk/ /etc/asterisk/pjsip_wizard.conf

chmod -R 755 /etc/asterisk
chmod 750 /etc/asterisk/keys

sed -i 's/memory_limit = 128M/memory_limit = 256M/' /etc/opt/rh/rh-php56/php.ini

exit 0
