#!/bin/bash

# check if fpbx is already installed
if [[ -f /var/www/html/freepbx/index.php ]] ; then
    exit 0
fi

source /opt/rh/rh-php56/enable

# run install
pass=$(perl -e  'use NethServer::Password; print NethServer::Password::store('mysql');')
cd /usr/src/freepbx
./install --dbuser root --dbpass $pass --webroot /var/www/html/freepbx -n >> /var/log/freepbx_rpm_install.log 2>&1

/usr/bin/mysql --defaults-file=/root/.my.cnf -N --batch asterisk -e 'SELECT `data` FROM `module_xml` WHERE `id`="randomid"' > /etc/asterisk/freepbx-id

# refresh fpbx signatures of files and reload
echo -e "[modules]\nautoload=yes" >> /etc/asterisk/asterisk.conf
/usr/sbin/fwconsole chown >> /var/log/freepbx_rpm_install.log 2>&1
exec /usr/sbin/fwconsole r >> /var/log/freepbx_rpm_install.log 2>&1

